<a href="https://colab.research.google.com/github/sangjunlim-dev/ml-practicals/blob/main/pandas_essentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('world_pop.csv')

df

# DataFrame Inspection
# df.columns
# df.info()
# df.shape
# df.describe(include=['object'])
# df['COLUMN'].value_counts(normalize=True)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
0,36,AFG,Afghanistan,Kabul,Asia,41128771.0,38972230.0,33753499.0,28189672.0,19542982.0,10694796.0,12486631.0,10752971.0,652230.0,63.0587,1.0257,0.52
1,138,ALB,Albania,Tirana,Europe,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
2,34,DZA,Algeria,Algiers,Africa,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
3,213,ASM,American Samoa,Pago Pago,Oceania,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
4,203,AND,Andorra,Andorra la Vella,Europe,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
229,226,WLF,Wallis and Futuna,Mata-Utu,Oceania,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
230,172,ESH,Western Sahara,El Aaiún,Africa,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
231,46,YEM,Yemen,Sanaa,Asia,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
232,63,ZMB,Zambia,Lusaka,Africa,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
233,74,ZWE,Zimbabwe,Harare,Africa,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

### Adding, Removing and Modifying Columns

In [ ]:
df4 = df.copy()

# Modifying an existing column
df4['World Population Percentage'] *= 100

# Adding a new columns
df4['Population (Before 2000)'] = df4['1970 Population'] + df4['1980 Population'] + df4['1970 Population']

In [ ]:
df5 = df.copy()

df5.set_index('CCA3', inplace=True)

# Removing a row
df4.drop('AFG', inplace=True)

# Removing columns
df5.drop(['Capital', 'Continent'], axis=1, inplace=True)

df5

,Rank,Country,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
CCA3,,,,,,,,,,,,,,
ALB,138,Albania,2842321.0,2866849.0,2882481.0,2913399.0,3182021.0,3295066.0,2941651.0,2324731.0,28748.0,98.8702,0.9957,0.04
DZA,34,Algeria,44903225.0,43451666.0,39543154.0,35856344.0,30774621.0,25518074.0,18739378.0,13795915.0,2381741.0,18.8531,1.0164,0.56
ASM,213,American Samoa,44273.0,46189.0,51368.0,54849.0,58230.0,47818.0,32886.0,27075.0,199.0,222.4774,0.9831,0.00
AND,203,Andorra,79824.0,77700.0,71746.0,71519.0,66097.0,53569.0,35611.0,19860.0,468.0,170.5641,1.0100,0.00
AGO,42,Angola,35588987.0,33428485.0,28127721.0,23364185.0,16394062.0,11828638.0,8330047.0,6029700.0,1246700.0,28.5466,1.0315,0.45
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
WLF,226,Wallis and Futuna,11572.0,11655.0,12182.0,13142.0,14723.0,13454.0,11315.0,9377.0,142.0,81.4930,0.9953,0.00
ESH,172,Western Sahara,575986.0,556048.0,491824.0,413296.0,270375.0,178529.0,116775.0,76371.0,266000.0,2.1654,1.0184,0.01
YEM,46,Yemen,33696614.0,32284046.0,28516545.0,24743946.0,18628700.0,13375121.0,9204938.0,6843607.0,527968.0,63.8232,1.0217,0.42
ZMB,63,Zambia,20017675.0,18927715.0,NaN,13792086.0,9891136.0,7686401.0,5720438.0,4281671.0,752612.0,26.5976,1.0280,0.25
ZWE,74,Zimbabwe,16320537.0,15669666.0,14154937.0,12839771.0,11834676.0,10113893.0,7049926.0,5202918.0,390757.0,41.7665,1.0204,0.20

### Cleaning

In [ ]:
df6 = df.copy()

### Filtering and Sorting

In [ ]:
# Filter out based on values
df[df['Rank'] < 10]

code = ['USA', 'CAN']
df[df['CCA3'].isin(code)]

df[df['CCA3'].str.contains('C')]

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
34,53,CMR,Cameroon,Yaounde,Africa,2.791454e+07,2.649109e+07,2.301265e+07,1.987804e+07,1.509159e+07,1.143052e+07,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35
35,39,CAN,Canada,Ottawa,North America,3.845433e+07,3.788870e+07,3.573213e+07,3.396341e+07,3.068331e+07,2.765720e+07,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48
36,171,CPV,Cape Verde,Praia,Africa,5.931490e+05,5.826400e+05,5.521660e+05,5.212120e+05,4.582510e+05,3.645630e+05,317234.0,287262.0,4033.0,147.0739,1.0089,0.01
37,205,CYM,Cayman Islands,George Town,North America,6.870600e+04,6.731100e+04,6.091100e+04,5.407400e+04,3.965800e+04,2.602700e+04,17100.0,10533.0,264.0,260.2500,1.0084,0.00
38,117,CAF,Central African Republic,Bangui,Africa,5.579144e+06,5.343020e+06,4.819333e+06,4.660067e+06,3.759170e+06,2.809221e+06,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07
39,69,TCD,Chad,N'Djamena,Africa,1.772332e+07,1.664470e+07,1.414027e+07,1.189473e+07,8.259137e+06,5.827069e+06,4408230.0,3667394.0,1284000.0,13.8032,1.0316,0.22
40,65,CHL,Chile,Santiago,South America,1.960373e+07,1.930032e+07,1.787012e+07,1.700416e+07,1.535180e+07,1.334287e+07,11469828.0,9820481.0,756102.0,25.9274,1.0057,0.25
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
42,28,COL,Colombia,Bogota,South America,5.187402e+07,5.093066e+07,4.711973e+07,NaN,3.921514e+07,3.260139e+07,26176195.0,20905254.0,1141748.0,45.4339,1.0069,0.65
43,163,COM,Comoros,Moroni,Africa,8.367740e+05,8.061660e+05,7.302160e+05,6.560240e+05,5.367580e+05,4.311190e+05,328328.0,242351.0,1862.0,449.3953,1.0184,0.01
44,223,COK,Cook Islands,Avarua,Oceania,1.701100e+04,1.702900e+04,1.769500e+04,1.721200e+04,1.589700e+04,1.712300e+04,17651.0,20470.0,236.0,72.0805,1.0005,0.00
45,124,CRI,Costa Rica,San José,North America,5.180829e+06,5.123105e+06,4.895242e+06,4.622252e+06,3.979193e+06,3.158253e+06,2414303.0,1855697.0,51100.0,101.3861,1.0052,0.06
47,85,CUB,Cuba,Havana,North America,1.121219e+07,1.130070e+07,1.133989e+07,1.129042e+07,1.110579e+07,1.062668e+07,9809107.0,8869636.0,109884.0,102.0366,0.9961,0.14
48,189,CUW,Curacao,Willemstad,North America,1.911630e+05,1.892880e+05,1.695720e+05,1.593800e+05,1.414240e+05,1.554460e+05,156851.0,150385.0,444.0,430.5473,1.0043,0.00
49,158,CYP,Cyprus,Nicosia,Europe,1.251488e+06,1.237537e+06,1.187280e+06,1.129686e+06,9.482370e+05,7.885000e+05,679327.0,640804.0,9251.0,135.2814,1.0059,0.02
50,88,CZE,Czech Republic,Prague,Europe,1.049399e+07,1.053095e+07,1.052380e+07,1.046475e+07,1.023471e+07,1.030119e+07,10270060.0,9795744.0,78865.0,133.0627,0.9984,0.13
55,15,COD,DR Congo,Kinshasa,Africa,9.901021e+07,9.285316e+07,7.865690e+07,6.639126e+07,4.861632e+07,3.598754e+07,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24
56,67,ECU,Ecuador,Quito,South America,1.800100e+07,1.758860e+07,1.619590e+07,1.498958e+07,1.262651e+07,1.044984e+07,8135845.0,6172215.0,276841.0,65.0229,1.0114,0.23
77,90,GRC,Greece,Athens,Europe,1.038497e+07,1.051223e+07,1.080664e+07,1.103378e+07,1.103811e+07,1.030226e+07,9307148.0,8544873.0,131990.0,78.6800,0.9942,0.13
100,52,CIV,Ivory Coast,Yamoussoukro,Africa,2.816054e+07,2.681179e+07,2.359674e+07,2.112004e+07,1.679967e+07,1.191054e+07,8303809.0,5477086.0,322463.0,NaN,NaN,0.35
119,167,MAC,Macau,Concelho de Macau,Asia,6.951680e+05,6.762830e+05,6.152390e+05,5.572970e+05,4.318960e+05,3.502270e+05,245332.0,247284.0,30.0,23172.2667,1.0125,0.01
134,217,MCO,Monaco,Monaco,Europe,3.646900e+04,3.692200e+04,3.676000e+04,3.317800e+04,3.246500e+04,3.032900e+04,27076.0,24270.0,2.0,18234.5000,0.9941,0.00
145,185,NCL,New Caledonia,Nouméa,Oceania,2.899500e+05,2.864030e+05,2.830320e+05,2.614260e+05,2.215370e+05,1.772640e+05,148599.0,110982.0,18575.0,15.6097,1.0075,0.00
147,106,NIC,Nicaragua,Managua,North America,6.948392e+06,6.755895e+06,6.298598e+06,5.855734e+06,5.123222e+06,4.227820e+06,3303309.0,2444767.0,130373.0,53.2962,1.0143,0.09
168,114,COG,Republic of the Congo,Brazzaville,Africa,5.970424e+06,5.702174e+06,5.064386e+06,4.437884e+06,3.134030e+06,2.385435e+06,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07
175,190,LCA,Saint Lucia,Castries,North America,1.798570e+05,1.792370e+05,1.756230e+05,1.709350e+05,1.595000e+05,1.423010e+05,121633.0,103090.0,616.0,291.9756,1.0011,0.00
178,199,VCT,Saint Vincent and the Grenadines,Kingstown,North America,1.039480e+05,1.046320e+05,1.064820e+05,1.093080e+05,1.138130e+05,1.124870e+05,107480.0,98459.0,389.0,267.2185,0.9963,0.00
185,196,SYC,Seychelles,Victoria,Africa,1.071180e+05,1.055300e+05,9.924000e+04,9.240900e+04,8.006000e+04,7.105700e+04,65290.0,54379.0,452.0,236.9867,1.0061,0.00
201,101,CHE,Switzerland,Bern,Europe,8.740472e+06,8.638613e+06,8.281732e+06,7.822435e+06,7.182059e+06,6.711693e+06,6319113.0,6181227.0,41284.0,211.7157,1.0056,0.11
215,212,TCA,Turks and Caicos Islands,Cockburn Town,North America,4.570300e+04,4.427600e+04,3.653800e+04,2.972600e+04,1.874400e+04,1.170900e+04,7598.0,5665.0,948.0,48.2099,1.0131,0.00

In [21]:
# Can directly set the index when reading in data using index_col
df2 = df.set_index('Country')

# Reset index
# df2.reset_index(inplace=True)

# Set multiple index
df3 = df.set_index(['Continent', 'Country'])

df3

                             Rank CCA3           Capital  2022 Population  \
Continent Country
Asia      Afghanistan          36  AFG             Kabul       41128771.0
Europe    Albania             138  ALB            Tirana        2842321.0
Africa    Algeria              34  DZA           Algiers       44903225.0
Oceania   American Samoa      213  ASM         Pago Pago          44273.0
Europe    Andorra             203  AND  Andorra la Vella          79824.0
...                           ...  ...               ...              ...
Oceania   Wallis and Futuna   226  WLF          Mata-Utu          11572.0
Africa    Western Sahara      172  ESH          El Aaiún         575986.0
Asia      Yemen                46  YEM             Sanaa       33696614.0
Africa    Zambia               63  ZMB            Lusaka       20017675.0
          Zimbabwe             74  ZWE            Harare       16320537.0

                             2020 Population  2015 Population  \
Continent Country
Asia      Afghanistan             38972230.0       33753499.0
Europe    Albania                  2866849.0        2882481.0
Africa    Algeria                 43451666.0       39543154.0
Oceania   American Samoa             46189.0          51368.0
Europe    Andorra                    77700.0          71746.0
...                                      ...              ...
Oceania   Wallis and Futuna          11655.0          12182.0
Africa    Western Sahara            556048.0         491824.0
Asia      Yemen                   32284046.0       28516545.0
Africa    Zambia                  18927715.0              NaN
          Zimbabwe                15669666.0       14154937.0

                             2010 Population  2000 Population  \
Continent Country
Asia      Afghanistan             28189672.0       19542982.0
Europe    Albania                  2913399.0        3182021.0
Africa    Algeria                 35856344.0       30774621.0
Oceania   American Samoa             54849.0          58230.0
Europe    Andorra                    71519.0          66097.0
...                                      ...              ...
Oceania   Wallis and Futuna          13142.0          14723.0
Africa    Western Sahara            413296.0         270375.0
Asia      Yemen                   24743946.0       18628700.0
Africa    Zambia                  13792086.0        9891136.0
          Zimbabwe                12839771.0       11834676.0

                             1990 Population  1980 Population  \
Continent Country
Asia      Afghanistan             10694796.0       12486631.0
Europe    Albania                  3295066.0        2941651.0
Africa    Algeria                 25518074.0       18739378.0
Oceania   American Samoa             47818.0          32886.0
Europe    Andorra                    53569.0          35611.0
...                                      ...              ...
Oceania   Wallis and Futuna          13454.0          11315.0
Africa    Western Sahara            178529.0         116775.0
Asia      Yemen                   13375121.0        9204938.0
Africa    Zambia                   7686401.0        5720438.0
          Zimbabwe                10113893.0        7049926.0

                             1970 Population  Area (km²)  Density (per km²)  \
Continent Country
Asia      Afghanistan             10752971.0    652230.0            63.0587
Europe    Albania                  2324731.0     28748.0            98.8702
Africa    Algeria                 13795915.0   2381741.0            18.8531
Oceania   American Samoa             27075.0       199.0           222.4774
Europe    Andorra                    19860.0       468.0           170.5641
...                                      ...         ...                ...
Oceania   Wallis and Futuna           9377.0       142.0            81.4930
Africa    Western Sahara             76371.0    266000.0             2.1654
Asia      Yemen                    6843607.0    527968.0            63.8232
Africa    Zambia                   4281671.0    752612.0            26.5976
          Zimbabwe                 5202918.0    390757.0            41.7665

                             Growth Rate  World Population Percentage
Continent Country
Asia      Afghanistan             1.0257                         0.52
Europe    Albania                 0.9957                         0.04
Africa    Algeria                 1.0164                         0.56
Oceania   American Samoa          0.9831                         0.00
Europe    Andorra                 1.0100                         0.00
...                                  ...                          ...
Oceania   Wallis and Futuna       0.9953                         0.00
Africa    Western Sahara          1.0184                         0.01
Asia      Yemen                   1.0217                         0.42
Africa    Zambia                  1.0280                         0.25
          Zimbabwe                1.0204                         0.20

[234 rows x 15 columns]

In [ ]:
# Filter based on column (default)
df2.filter(['Rank', 'CCA3'], axis=1)

# Filter based on row
df2.filter(['Canada'], axis=0)

# Row index containing 'United'
df2.filter(like='United', axis=0)

,Rank,CCA3,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
Country,,,,,,,,,,,,,,,,
United Arab Emirates,97,ARE,Abu Dhabi,Asia,9441129.0,9287289.0,8916899.0,8481771.0,3275333.0,1900151.0,1014048.0,298084.0,83600.0,112.9322,1.0081,0.12
United Kingdom,21,GBR,London,Europe,67508936.0,67059474.0,65224364.0,62760039.0,58850043.0,57210442.0,56326328.0,55650166.0,242900.0,277.9289,1.0034,0.85
United States,3,USA,"Washington, D.C.",North America,338289857.0,335942003.0,324607776.0,311182845.0,282398554.0,248083732.0,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
United States Virgin Islands,200,VIR,Charlotte Amalie,North America,99465.0,100442.0,102803.0,106142.0,108185.0,100685.0,96640.0,63446.0,347.0,286.6427,0.9937,0.00

In [ ]:
# Fetch based on integer position
df2.iloc[3]

# Fetch based on index label (initial index)
df2.loc['Canada']

Rank                                      39
CCA3                                     CAN
Capital                               Ottawa
Continent                      North America
2022 Population                   38454327.0
2020 Population                   37888705.0
2015 Population                   35732126.0
2010 Population                   33963412.0
2000 Population                   30683313.0
1990 Population                   27657204.0
1980 Population                   24511510.0
1970 Population                   21434577.0
Area (km²)                         9984670.0
Density (per km²)                     3.8513
Growth Rate                           1.0078
World Population Percentage             0.48
Name: Canada, dtype: object

In [ ]:
df[df['Rank'] < 10].sort_values(by='Rank', ascending=True)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88
92,2,IND,India,New Delhi,Asia,1.417173e+09,1.396387e+09,1.322867e+09,1.240614e+09,1.059634e+09,NaN,NaN,557501301.0,3287590.0,431.0675,1.0068,17.77
221,3,USA,United States,"Washington, D.C.",North America,3.382899e+08,3.359420e+08,3.246078e+08,3.111828e+08,2.823986e+08,2.480837e+08,223140018.0,200328340.0,9372610.0,36.0935,1.0038,4.24
93,4,IDN,Indonesia,Jakarta,Asia,2.755013e+08,2.718580e+08,2.590920e+08,2.440162e+08,2.140724e+08,1.821599e+08,148177096.0,115228394.0,1904569.0,144.6529,1.0064,3.45
156,5,PAK,Pakistan,Islamabad,Asia,2.358249e+08,2.271967e+08,2.109693e+08,1.944545e+08,1.543699e+08,1.154141e+08,80624057.0,59290872.0,881912.0,267.4018,1.0191,2.96
149,6,NGA,Nigeria,Abuja,Africa,2.185412e+08,2.083274e+08,1.839958e+08,1.609529e+08,1.228520e+08,9.521426e+07,72951439.0,55569264.0,923768.0,236.5759,1.0241,2.74
27,7,BRA,Brazil,Brasilia,South America,2.153135e+08,2.131963e+08,2.051882e+08,1.963535e+08,1.758737e+08,1.507064e+08,122288383.0,96369875.0,8515767.0,25.2841,1.0046,2.70
16,8,BGD,Bangladesh,Dhaka,Asia,1.711864e+08,1.674210e+08,1.578300e+08,1.483911e+08,1.291933e+08,1.071477e+08,83929765.0,67541860.0,147570.0,1160.0350,1.0108,2.15
171,9,RUS,Russia,Moscow,Europe,1.447133e+08,1.456173e+08,1.446684e+08,1.432426e+08,1.468448e+08,1.480057e+08,138257420.0,130093010.0,17098242.0,8.4636,0.9973,1.81

In [ ]:
# Sorting based on index
df3.sort_index()

# Must use all the index labels (multiple indexes) when fecthing a value
df3.loc['North America', 'Canada']

Rank                                   39
CCA3                                  CAN
Capital                            Ottawa
2022 Population                38454327.0
2020 Population                37888705.0
2015 Population                35732126.0
2010 Population                33963412.0
2000 Population                30683313.0
1990 Population                27657204.0
1980 Population                24511510.0
1970 Population                21434577.0
Area (km²)                      9984670.0
Density (per km²)                  3.8513
Growth Rate                        1.0078
World Population Percentage          0.48
Name: (North America, Canada), dtype: object

### Apply Functions

In [18]:
df7 = df.copy()

# Apply functions to each column (operate on rows - axis=0)
df7.apply(np.max)

df7[df7['CCA3'].apply(lambda code: code.startswith('C'))].head()

# Replace values in a column with map and dictionary
# Similar to replace function, however this method will change them to NaN if value isn't present in the dictionary
df7['TF'] = df7['CCA3'].apply(lambda code: 'Yes' if code.startswith('C') else 'No')
d = {'Yes': True, 'No': False}

df7['TF'] = df7['TF'].map(d)

,Rank,CCA3,Country,Capital,Continent,2022 Population,2020 Population,2015 Population,2010 Population,2000 Population,1990 Population,1980 Population,1970 Population,Area (km²),Density (per km²),Growth Rate,World Population Percentage,TF
34,53,CMR,Cameroon,Yaounde,Africa,2.791454e+07,2.649109e+07,2.301265e+07,1.987804e+07,1.509159e+07,1.143052e+07,8519891.0,6452787.0,475442.0,58.7128,1.0263,0.35,True
35,39,CAN,Canada,Ottawa,North America,3.845433e+07,3.788870e+07,3.573213e+07,3.396341e+07,3.068331e+07,2.765720e+07,24511510.0,21434577.0,9984670.0,3.8513,1.0078,0.48,True
36,171,CPV,Cape Verde,Praia,Africa,5.931490e+05,5.826400e+05,5.521660e+05,5.212120e+05,4.582510e+05,3.645630e+05,317234.0,287262.0,4033.0,147.0739,1.0089,0.01,True
37,205,CYM,Cayman Islands,George Town,North America,6.870600e+04,6.731100e+04,6.091100e+04,5.407400e+04,3.965800e+04,2.602700e+04,17100.0,10533.0,264.0,260.2500,1.0084,0.00,True
38,117,CAF,Central African Republic,Bangui,Africa,5.579144e+06,5.343020e+06,4.819333e+06,4.660067e+06,3.759170e+06,2.809221e+06,2415276.0,2067356.0,622984.0,8.9555,1.0224,0.07,True
40,65,CHL,Chile,Santiago,South America,1.960373e+07,1.930032e+07,1.787012e+07,1.700416e+07,1.535180e+07,1.334287e+07,11469828.0,9820481.0,756102.0,25.9274,1.0057,0.25,True
41,1,CHN,China,Beijing,Asia,1.425887e+09,1.424930e+09,1.393715e+09,1.348191e+09,1.264099e+09,1.153704e+09,982372466.0,822534450.0,9706961.0,146.8933,1.0000,17.88,True
42,28,COL,Colombia,Bogota,South America,5.187402e+07,5.093066e+07,4.711973e+07,NaN,3.921514e+07,3.260139e+07,26176195.0,20905254.0,1141748.0,45.4339,1.0069,0.65,True
43,163,COM,Comoros,Moroni,Africa,8.367740e+05,8.061660e+05,7.302160e+05,6.560240e+05,5.367580e+05,4.311190e+05,328328.0,242351.0,1862.0,449.3953,1.0184,0.01,True
44,223,COK,Cook Islands,Avarua,Oceania,1.701100e+04,1.702900e+04,1.769500e+04,1.721200e+04,1.589700e+04,1.712300e+04,17651.0,20470.0,236.0,72.0805,1.0005,0.00,True
45,124,CRI,Costa Rica,San José,North America,5.180829e+06,5.123105e+06,4.895242e+06,4.622252e+06,3.979193e+06,3.158253e+06,2414303.0,1855697.0,51100.0,101.3861,1.0052,0.06,True
47,85,CUB,Cuba,Havana,North America,1.121219e+07,1.130070e+07,1.133989e+07,1.129042e+07,1.110579e+07,1.062668e+07,9809107.0,8869636.0,109884.0,102.0366,0.9961,0.14,True
48,189,CUW,Curacao,Willemstad,North America,1.911630e+05,1.892880e+05,1.695720e+05,1.593800e+05,1.414240e+05,1.554460e+05,156851.0,150385.0,444.0,430.5473,1.0043,0.00,True
49,158,CYP,Cyprus,Nicosia,Europe,1.251488e+06,1.237537e+06,1.187280e+06,1.129686e+06,9.482370e+05,7.885000e+05,679327.0,640804.0,9251.0,135.2814,1.0059,0.02,True
50,88,CZE,Czech Republic,Prague,Europe,1.049399e+07,1.053095e+07,1.052380e+07,1.046475e+07,1.023471e+07,1.030119e+07,10270060.0,9795744.0,78865.0,133.0627,0.9984,0.13,True
55,15,COD,DR Congo,Kinshasa,Africa,9.901021e+07,9.285316e+07,7.865690e+07,6.639126e+07,4.861632e+07,3.598754e+07,26708686.0,20151733.0,2344858.0,42.2244,1.0325,1.24,True
100,52,CIV,Ivory Coast,Yamoussoukro,Africa,2.816054e+07,2.681179e+07,2.359674e+07,2.112004e+07,1.679967e+07,1.191054e+07,8303809.0,5477086.0,322463.0,NaN,NaN,0.35,True
168,114,COG,Republic of the Congo,Brazzaville,Africa,5.970424e+06,5.702174e+06,5.064386e+06,4.437884e+06,3.134030e+06,2.385435e+06,1829256.0,1396989.0,342000.0,17.4574,1.0231,0.07,True
201,101,CHE,Switzerland,Bern,Europe,8.740472e+06,8.638613e+06,8.281732e+06,7.822435e+06,7.182059e+06,6.711693e+06,6319113.0,6181227.0,41284.0,211.7157,1.0056,0.11,True

### Grouping
```df.groupby(by=GROUPING_COLUMN)[COLUMN_TO_SHOW].function()```

In [15]:
df8 = df.copy()

# The grouping column becomes a new index
df8.groupby(['Continent']).describe()

df8.groupby(['Continent']).agg({'2022 Population': ['mean']}).sort_values(by=('2022 Population', 'mean'), ascending=False)

              2022 Population
                         mean
Continent
Asia             9.632739e+07
South America    3.120119e+07
Africa           2.545588e+07
Europe           1.505537e+07
North America    1.500740e+07
Oceania          2.046386e+06

### Summary Tables

In [22]:
df9 = df.copy()

df9['2022 Population'].mean()

df9['Avg Population'] = (df9['2022 Population'] > 34632250).astype('int')

pd.crosstab(df9['Continent'], df9['Avg Population'], margins=True)

Avg Population    0   1  All
Continent
Africa           45  12   57
Asia             34  16   50
Europe           42   8   50
North America    37   3   40
Oceania          23   0   23
South America    11   3   14
All             192  42  234